### ISSUE TITLE
re-vamp Domains

### ISSUE THREAD

**Issue by bansp** [clarin-eric/standards#356]
https://standards.clarin.eu/sis/views/list-domains.xq

Things to do:

- [ ] make "uncategorized" actually uncategorised, so with the `@sortBy` either absent or set to empty string
   - basically, accept the fact that metadomains are merely helpful rather than obligatory
- [ ] remove the metacategory "Databases", because it's misleading (#349)
- [ ] possibly add a "source code" domain (in this way, handle #265)
- [ ] add domains for experimental data depositions (as in the CH consortium, consult @acraevschi )
- [ ] consider renaming "Documentation" (maybe just by adding an attribute), so that it is not confused with Language Documentation, which obviously needs more than one domain; if possible, consult @hannahedeland 
- [ ] add ML-related domains (does 'data-preparation', 'model-training', 'model-exchange' make sense?); if possible, consult @raspberryjoy 
- [ ] describe/gloss them better (including 
- [ ] possibly add archeological-data-related domains (DARIAH but also ARCHE)
- [ ] align with Re3Data content type (#241)
- check the link to the [SIS:Domains](https://github.com/clarin-eric/standards/issues?q=is%3Aissue+is%3Aopen+label%3ASIS%3Adomains) label for potential additional issues

**Comment by bansp** [comment]
Meeting decision: push to the next milestone, given that some dependent issues are already there.
